### ISSUE TITLE
Fix Firefox in Windows UI

### ISSUE THREAD

**Issue by Gitoffthelawn** [zvxr-tech/tabs2txt#4]
Here is how it looks:

![zvxr](https://cloud.githubusercontent.com/assets/7672848/25735661/c0f0bdf0-3121-11e7-98ad-7d4d71b9103e.png)

Notice:
 - extra gray horizontal bar
 - unneeded horizontal scrollbar

**Comment by zvxr-tech** [comment]
Fixed with May 8, 2017 commit (0220979ca21df10005823d65364e65b7e1afa9d2).

**Comment by Gitoffthelawn** [comment]
Thanks! 👍
